spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  banner:
    location: classpath:static/banner.txt
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      fail-on-empty-beans: false

app:
  fire:
    config: classpath:static/fire-config.json

booky:
  openapi:
    prod-url: ${PROVIDER}

    dev-url: http://localhost:8080/
